(lang dune 2.8)

(name using-postgres-with-ocaml)

(generate_opam_files true)

(package
 (name using-postgres-with-ocaml)
 (depends
  (ocaml
   (>= "4.08.0"))
  opium
  ppx_deriving_yojson
  yojson
  uuidm
  caqti
  caqti-lwt
  caqti-driver-postgresql
  ppx_rapper
  ppx_rapper_lwt))
