(lang dune 2.8)

(name parser-for-kids-in-ocaml-with-menhir)

(generate_opam_files true)

(package
 (name parser-for-kids-in-ocaml-with-menhir)
 (depends
  (ocaml
   (>= "4.08.0"))
  ppx_deriving
  menhir))
